go:
  - 1.5
  - 1.6
  - tip

os:
  - linux

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
